default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: appointment_management_system_development

test:
  <<: *default
  database: appointment_management_system_test

production:
  primary: &primary_production
    <<: *default
    database: appointment_management_system_production
    username: appointment_management_system
    password: <%= ENV["APPOINTMENT_MANAGEMENT_SYSTEM_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: appointment_management_system_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: appointment_management_system_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: appointment_management_system_production_cable
    migrations_paths: db/cable_migrate
